<?php 	
 ?>
<!-- Got there from finalSlipPage -->
 <!DOCTYPE html>
 <html>
 <head>
 	<title>	Pay Slip</title>
 </head>
 <body >
 	<script type="">
 		printing(){
 			window.print();
 		}
 	</script>
 		<meta name="viewport" content="width=device-width, initial-scale=1">
	  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
	  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
	  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
	  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
	  	<div class="container border p-3" id="mainPrint">
	  	<div class="m-3">	
	  		<!-- Row No 1 -->
	  		<div class="row">
	  		<h4 class="text-danger"><?php echo $message; ?></h4>
	  		</div>
	  		<div class="row">
	  			<h4>Pay Generation Date : </h4> <h4 class="ml-4"><?php echo "  ".$emb_date; ?></h4>
	  		</div>
	  		<div class="row">
	  			<h4>Employee Name : </h4> <h4 class="ml-4"><?php echo "  ".$emp_name; ?></h4> 
	  		</div>
	  		<div class="row">
	  			<h4>Email : </h4> <h4 class="ml-4"><?php echo "  ".$emp_email; ?></h4> 
	  		</div>
	  		<div class="row">
	  			<h4>Id Card : </h4> <h4 class="ml-4"><?php echo "  ".$emp_idCard; ?></h4> 
	  		</div>
	  		<hr>	
	  	</div>

	  		<div class="row">
	  			<h5 class="text-info">Amount Details</h5>
	  		</div>	
	  		<div class="row">
	  			<table class='table  table-bordered table-hover'>	
	  				<thead class='table-dark'>
				<tr>
					<th>Basic</th>
					<th>Travel Allowance</th>
					<th>Medical Allowance</th>
					<th>Bonus</th>
				</tr>
				</thead>
				<tr>
					<td><?php echo $grade_basic." /-"; ?></td>
					<td><?php echo $grade_ta." /-"; ?></td>
					<td><?php echo $grade_ma." /-"; ?></td>
					<td><?php echo $grade_bonus." /-"; ?></td>
				</tr>

	  			</table>
	  		</div>	
	  		<hr>	
	  		<div class="row">
	  			<h5 class="text-info"> Deduction Amount</h5>
	  		</div>	
	  		<div class="row">
	  			<table class='table  table-bordered table-hover'>	
	  				<thead class='table-dark'>
				<tr>
					<th>House Rent</th>
					<th>Professional Tax</th>
					<
				</tr>
				</thead>
				<tr>
					<td><?php echo $grade_hr." /-"; ?></td>
					<td><?php echo $grade_ptax." /-"; ?></td>
					
				</tr>

	  			</table>
	  		</div>
	  		<hr>	
	  		<div>
	  			<div class="p-3" >	
	  					<div class="row justify-content-end">
	  						<h4 >Gross Pay :</h4> <h4 class="pl-3"><u><?php echo $emp_gross.' /-'?></u></h4>
	  					</div>
	  					<div class="row justify-content-end">
	  						<h4 >Total Pay :</h4> <h4 class="pl-3"><u><?php echo $emp_total.' /-'?></u></h4>
	  					</div>
	  					<div class="row ">
	  						<?php 	$mon = strtoupper($sal_mon);
	  								$year = strtoupper($sal_year);
	  						 ?>
	  						<h5><em>Salary Month : </em></h5> <h5 class="pl-3"><em><?php echo "'".$mon."'"?></em></h5>
	  					</div>
	  					<div class="row ">
	  						<h5><em> Salary Year :</em></h5> <h5 class="pl-3"><em><?php echo "'".$year."'"?></em></h5>
	  					</div>

	  			</div>
	  			<hr>	

	  		</div>
	  			<footer class="bg-dark text-white border">
	  				<div class="row p-3">
	  				<p ><em>*Compter Generated Slip</em></p>
	  				<p class="pl-3"><em>*Generated By Admin</em></p>
	  				<p class="pl-3"><em>*<?php if($message != "")
	  				{
	  					echo "This Slip Is Only Copy, It Is not accepted !";
	  				} ?></em></p>
	  				
	  				</div>
	  			</footer>
	  			
		</div>
 </body>
 </html>
